services:

  server:
    build:
      context: ..
      dockerfile: ./containers/nginx.dockerfile
    image: nginx:stable-alpine-slim
    container_name: brDev_server
    network_mode: "host"
    # ports: "5000:5000" # Unused with the 'host' network_mode
    volumes:
      - ../dist/:/var/www/html/:ro

  postgres:
    image: postgres:alpine
    container_name: brDev_psql
    ports: "5002:5432"
    environment:
      - POSTGRES_PASSWORD=hunter2
      - POSTGRES_USER=businessman
      - POSTGRES_DB=BusinessRoadDev

  valkey:
    image: valkey:alpine
    container_name: brDev_valkey
    ports: "5003:6379"
